#DB
services:

  postgres:
    image: postgres:16-bookworm
    ports:
    - 5432:5432
    environment:
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: postgres
      POSTGRES_DB: cryptoWallet  # This sets the database name